### ISSUE TITLE
./configure fails on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by jordancurve** [gregfjohnson/aplette#1]
`sh configure` gives this error:

```
sed: 35: conftest.s1: filename expected
```

Then `make` fails with:

```
make: *** No targets.  Stop.
```

That's using the built-in `/usr/bin/sed`. After I installed GNU sed, I got this error instead:

```
sed: file conftest.s1 line 36: missing filename in r/R/w/W commands
```

**Comment by jordancurve** [comment]
Here are the contents of `conftest.s1`: https://pastebin.com/mkHm02we

**Comment by waclena** [comment]
Same error (the GNU sed one) on Arch Linux.

**Comment by gregfjohnson** [comment]
Thanks!  I will check it out.

**Comment by gregfjohnson** [comment]
OK I fixed the configuration process, at least on Arch Linux.  I saw the reported error.  I don't have a Mac to confirm the change, but I hope and expect that the change will solve the Mac problem as well.  Please let me know if this is not the case.

**Comment by waclena** [comment]
Problem solved for me (Arch); tnx.
